### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by konaya** [sup-heliotrope/sup#535]
http://sup-heliotrope.github.io/ redirects to http://supmua.org/, and supmua.org doesn't have an A record so it doesn't lead anywhere.

**Comment by gauteh** [comment]
Should be fixed once the DNS records propagate.

**Comment by konaya** [comment]
Even taking into account DNS propagation – and disregarding the fact that DNS propagation doesn't take several days – you still seem to have issues with the website. A different issue, but still an issue. Querying the name servers for the domain directly and going with that result still doesn't yield a working web site.

```
konaya@wulfenite:~> whois supmua.org | grep Name\ Server
Name Server: C.DNS.GANDI.NET
Name Server: B.DNS.GANDI.NET
Name Server: A.DNS.GANDI.NET
konaya@wulfenite:~> dig @c.dns.gandi.net +noall +answer supmua.org
supmua.org.		10800	IN	A	192.30.252.153
supmua.org.		10800	IN	A	192.30.252.154
konaya@wulfenite:~> echo "192.30.252.153 supmua.org" | sudo tee -a /etc/hosts
konaya@wulfenite:~> curl -I http://supmua.org
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Sun, 14 May 2017 09:44:40 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 9116
ETag: "58a4d944-239c"
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
X-GitHub-Request-Id: A728:0CC1:198C933:214C0D6:59182708 
```

**Comment by gauteh** [comment]
Right, I meant to drop supmua.org and just use sup-heliotrope.github.com, but there must be something missing somewhere..

**Comment by gauteh** [comment]
sup-heliotrope.github.io should now work. Supmua is no longer active.


søn. 14. mai 2017 kl. 11.49 skrev Benjamin Tayehanpour <
notifications@github.com>:
